// lol-data.js — the patch registry at runtime (LolPatches) and the dataset
// loader (LolData), DESIGN §2.3-§2.4. Loaded in <head> right after
// patch-registry.js and before nav.js. No jQuery, and no DOM work at load
// time, so it runs before DOMContentLoaded.
//
// Reads the globals of patch-registry.js (generated by tools/build-registry.js):
//   SEASON_NAV, LOL_PAGE_DEFAULT, LOL_PATCHES, LOL_ALIASES, LOL_REGISTRY
//
// LolPatches
//   page()                        "masteries" | "runes" | "reforged":
//                                 html[data-lol-page], else location.pathname
//   entries(page)                 the listed entries, chronological
//   entry(page, id)               the canonical entry with this id, or null
//   resolve(page, id)             {entry, alias} or null, tried in this order:
//                                 (1) a listed id (alias null); (2) LOL_ALIASES
//                                 (alias = the record + {id}); (3) an id in the
//                                 page's pattern (m-V…, preReforged-V…,
//                                 rr-vX-Y) naming an unlisted patch inside the
//                                 page's listed range: the latest listed patch
//                                 at or before it (alias = {id, to, unlisted:
//                                 true}); unlisted patches carry no change, so
//                                 the data is the same. (4) null
//   fromHash(page[, hash])        the dataset a share link opens:
//                                 {hash, id, entry, alias, plain, bare, empty,
//                                 unknown}. Reads the first "|" segment. A hash
//                                 without "|" that resolve() accepts, or that
//                                 has the page's id pattern, is that id alone
//                                 (bare = true: the link holds no build, the
//                                 page opens empty; index.html#m-V4.5). Any
//                                 other mastery / rune hash without "|" is the
//                                 legacy plain form (LOL_ALIASES.plain).
//                                 Empty or unresolvable: the page default
//                                 (empty / unknown = true)
//   list(page, seasonKey)         that season's entries, chronological
//   seasonDefault(page, key)      entry | null
//   pageDefault(page)             entry | null
//   season(key), seasons()        SEASON_NAV records
//   pageOfId(id)                  the page an id belongs to (by its pattern;
//                                 legacy "sN-…" ids are masteries), or null
//   parse(patch), compare(a, b)   patch order (V1.0.0.118 < V1.0.0.118b,
//                                 V3.04 = V3.4, V25.S1.1 = V25.1, V26.01 = V26.1),
//                                 the same rules as tools/lib/patches.js
//   patchOfId(page, id)           the parsed patch an id names, or null
//   fillPatchSelect(select, page, seasonKey, selectedId)
//                                 one <option value=id>label</option> per entry
//                                 of the season, oldest first; select = element,
//                                 jQuery object or selector. Returns the count.
//                                 Then fires "lol:patch-select" on document,
//                                 detail {select, page, season, id, entry}: the
//                                 pages fill the header's Patch dropdown with it
//                                 whenever the patch on screen changes (and
//                                 refill it when a switch fails), so the header's
//                                 "What changed" control (nav.js) follows it
//
// LolData
//   register(kind, key, payload)  called by the generated data files; kind is
//                                 the page ("masteries", "runes", "reforged"),
//                                 "masteries-legacy" (legacy codecs) or "notes"
//                                 (data/notes/<page>-<season>.js: {patch: notes})
//   load(entry)                   Promise<dataset>: injects <script src=entry.file>
//                                 once per file, then resolves with
//                                 {...entry, ...payload} (one object per entry).
//                                 An entry with data: null resolves at once
//                                 with a copy of the entry. Rejects when the
//                                 file is missing (file: null = not built yet),
//                                 fails to load, or does not register entry.data
//   get(entry)                    the same dataset synchronously, or null
//   loadCodec(alias)              Promise<codec>: the legacy codec alias.codec,
//                                 loading LOL_REGISTRY.codecs on first use
//   getCodec(key)                 synchronous, or null
//   prefetch(entries)             idle-time injection of the files not loaded
//                                 yet, one at a time; best effort. Returns a
//                                 Promise that resolves when the queue is done
//   loadNotes(entry)              Promise<{summary, items, kind} | null>: the
//                                 entry's change notes from its season's notes
//                                 file (entry.notes.file, kind "notes", key
//                                 entry.notes.key), injected once. null = the
//                                 file has no notes for this patch. Rejects when
//                                 there is no file (notes.file: null = not built
//                                 yet) or it fails to load
//   getNotes(entry)               the same synchronously; undefined while the
//                                 file is not loaded, null when it has none
//   prefetchNotes(entries)        idle-time injection of their notes files (the
//                                 same queue as prefetch)
//
// lolPreloadDataset(page)         inline in <head>: document.writes the
//                                 <script> of the dataset the hash opens (and
//                                 legacy-codecs.js for a mastery alias), so it
//                                 is registered before the calculators' ready
//                                 handlers run. After parsing (or where
//                                 document.write is blocked) it injects instead.
//                                 Returns the fromHash() result.
//
// Local data is only ever loaded with <script src> (works over file:// and
// http); never with fetch / XHR.

var LolPatches = window.LolPatches = (function(){
    var PAGES = ["masteries", "runes", "reforged"];
    var byId = null;

    function reg(name) { return typeof window[name] !== "undefined" ? window[name] : null; }
    function patchesOf(page) { var p = reg("LOL_PATCHES"); return (p && p[page]) || []; }

    function index() {
        if (byId) return byId;
        byId = Object.create(null);
        PAGES.forEach(function(page){
            var m = byId[page] = Object.create(null);
            patchesOf(page).forEach(function(e){ m[e.id] = e; });
        });
        return byId;
    }

    function page() {
        var el = document.documentElement;
        var attr = el && el.getAttribute("data-lol-page");
        if (attr && PAGES.indexOf(attr) >= 0) return attr;
        var p = location.pathname || "";
        if (/runes-reforged\.html$/i.test(p)) return "reforged";
        if (/runes\.html$/i.test(p)) return "runes";
        return "masteries";
    }

    // --- patch strings (the rules of tools/lib/patches.js parse/compare) --
    // -> { nums: [1,0,0,118] | [3,4] | [25,1], suffix: "" | "b" } or null.
    function parse(p) {
        if (p && typeof p === "object" && p.nums) return p;
        var s = String(p == null ? "" : p).replace(/^\s+|\s+$/g, "").replace(/^[vV]/, "");
        var m = /^(\d+)\.[sS](\d+)\.(\d+)$/.exec(s);                    // V25.S1.1 = 25.1
        if (m) return +m[1] === 25 && +m[2] === 1 && +m[3] >= 1 && +m[3] <= 3 ? { nums: [25, +m[3]], suffix: "" } : null;
        m = /^(\d+(?:\.\d+)*)(?:([a-zA-Z])|\(([a-zA-Z])\))?$/.exec(s);
        if (!m) return null;
        var nums = m[1].split(".").map(function(x){ return parseInt(x, 10); });
        var maj = nums[0], level = maj <= 1 ? 4 : 2;
        if (maj === 2 || (maj >= 15 && maj <= 24) || nums.length < level) return null;
        if (level === 2 && nums[1] === 0) return null;
        return { nums: nums.slice(0, level), suffix: (m[2] || m[3] || "").toLowerCase() };
    }

    function compare(a, b) {
        var pa = parse(a), pb = parse(b);
        if (!pa || !pb) throw new Error("LolPatches.compare: not a patch: " + (pa ? b : a));
        var n = Math.min(pa.nums.length, pb.nums.length);
        for (var i = 0; i < n; i++) if (pa.nums[i] !== pb.nums[i]) return pa.nums[i] < pb.nums[i] ? -1 : 1;
        if (pa.nums.length !== pb.nums.length) return pa.nums.length < pb.nums.length ? -1 : 1;
        if (pa.suffix === pb.suffix) return 0;
        return pa.suffix < pb.suffix ? -1 : 1;
    }

    var ID_RE = {
        masteries: /^m-(V[0-9][0-9A-Za-z.()]*)$/,
        runes: /^preReforged-(V[0-9][0-9A-Za-z.()]*)$/,
        reforged: /^rr-v(\d+)-(\d+)$/
    };

    function patchOfId(pg, id) {
        var m = ID_RE[pg] && ID_RE[pg].exec(String(id || ""));
        if (!m) return null;
        return parse(pg === "reforged" ? m[1] + "." + m[2] : m[1]);
    }

    function pageOfId(id) {
        id = String(id || "");
        if (/^m-V/.test(id) || /^s\d+-/.test(id)) return "masteries";
        if (/^preReforged-/.test(id)) return "runes";
        if (/^rr-/.test(id)) return "reforged";
        return null;
    }

    // --- lookups -------------------------------------------------------------
    function entries(pg) { return patchesOf(pg); }
    function entry(pg, id) { var m = index()[pg]; return (m && m[id]) || null; }

    function copy(o, extra) {
        var out = {}, k;
        for (k in o) if (Object.prototype.hasOwnProperty.call(o, k)) out[k] = o[k];
        for (k in extra) if (Object.prototype.hasOwnProperty.call(extra, k)) out[k] = extra[k];
        return out;
    }

    function resolve(pg, id) {
        if (id == null || id === "") return null;
        id = String(id);
        var e = entry(pg, id);
        if (e) return { entry: e, alias: null };
        var aliases = reg("LOL_ALIASES"), map = aliases && aliases[pg];
        var a = map && Object.prototype.hasOwnProperty.call(map, id) ? map[id] : null;
        if (a) {
            e = entry(pg, a.to);
            if (e) return { entry: e, alias: copy(a, { id: id }) };
        }
        var p = patchOfId(pg, id), list = entries(pg);
        if (!p || !list.length) return null;
        if (compare(p, list[0].patch) < 0 || compare(p, list[list.length - 1].patch) > 0) return null;
        var best = null;
        for (var i = 0; i < list.length; i++) {
            if (compare(list[i].patch, p) <= 0) best = list[i];
            else break;
        }
        return best ? { entry: best, alias: { id: id, to: best.id, unlisted: true } } : null;
    }

    function pageDefault(pg) {
        var d = reg("LOL_PAGE_DEFAULT");
        return d && d[pg] ? entry(pg, d[pg]) : null;
    }

    function seasons() { return reg("SEASON_NAV") || []; }
    function season(key) {
        var list = seasons();
        for (var i = 0; i < list.length; i++) if (list[i].key === key) return list[i];
        return null;
    }
    function seasonDefault(pg, key) {
        var s = season(key);
        return s && s[pg] ? entry(pg, s[pg]) : null;
    }
    function list(pg, key) {
        return entries(pg).filter(function(e){ return e.season === key; });
    }

    function fromHash(pg, hash) {
        pg = pg || page();
        var raw = String(hash == null ? location.hash : hash).replace(/^#/, "");
        var out = { hash: raw, id: null, entry: null, alias: null, plain: false, bare: false, empty: false, unknown: false };
        // Reforged links pasted through chat apps arrive percent-encoded
        // (runes-reforged.js parseReforgedHash does the same).
        if (pg === "reforged" && raw.indexOf("|") < 0 && /%7C|%2C/i.test(raw)) {
            try { raw = decodeURIComponent(raw); } catch (e) { raw = raw.replace(/%7C/gi, "|").replace(/%2C/gi, ","); }
        }
        if (!raw) {
            out.empty = true;
            out.entry = pageDefault(pg);
            return out;
        }
        var pipe = raw.indexOf("|");
        // An id alone: listed, alias or unlisted patch, with an empty build.
        // It can never be a plain code: the mastery code alphabet has no "."
        // (every m-V… id has one), a rune list is numbers, and the old ids
        // (s1-final …) are no code the plain writer could produce
        // (tools/test-links.js L0 checks both). An id of the page's pattern
        // outside the listed range (m-V1.0.0.10) is an unknown id, as it is
        // with a "|".
        if (pipe < 0) {
            var b = resolve(pg, raw);
            if (b || patchOfId(pg, raw)) {
                out.id = raw; out.bare = true;
                if (b) { out.entry = b.entry; out.alias = b.alias; }
                else { out.unknown = true; out.entry = pageDefault(pg); }
                return out;
            }
        }
        if (pipe < 0 && pg !== "reforged") {
            var aliases = reg("LOL_ALIASES"), plain = aliases && aliases.plain && aliases.plain[pg];
            out.plain = true;
            if (plain) {
                out.alias = copy(plain, { id: null, plain: true });
                out.entry = entry(pg, plain.to);
            }
            if (!out.entry) out.entry = pageDefault(pg);
            return out;
        }
        out.id = pipe < 0 ? raw : raw.slice(0, pipe);
        var r = resolve(pg, out.id);
        if (r) { out.entry = r.entry; out.alias = r.alias; }
        else { out.unknown = true; out.entry = pageDefault(pg); }
        return out;
    }

    function fillPatchSelect(select, pg, key, selectedId) {
        var el = select && select.jquery ? select[0]
            : typeof select === "string" ? document.querySelector(select) : select;
        if (!el) return 0;
        var r = selectedId ? resolve(pg, selectedId) : null;
        var want = r ? r.entry.id : selectedId;
        while (el.firstChild) el.removeChild(el.firstChild);
        var items = list(pg, key);
        items.forEach(function(e){
            var o = document.createElement("option");
            o.value = e.id;
            o.textContent = e.label;
            if (e.id === want) o.selected = true;
            el.appendChild(o);
        });
        if (want) el.value = want;
        if (typeof CustomEvent === "function" && document.dispatchEvent) {
            try {
                document.dispatchEvent(new CustomEvent("lol:patch-select", { detail: {
                    select: el, page: pg, season: key, id: want || null, entry: want ? entry(pg, want) : null } }));
            } catch (err) { /* a listener's error must not break the fill */ }
        }
        return items.length;
    }

    return {
        PAGES: PAGES,
        page: page, entries: entries, entry: entry, resolve: resolve, fromHash: fromHash,
        list: list, seasonDefault: seasonDefault, pageDefault: pageDefault,
        season: season, seasons: seasons, pageOfId: pageOfId,
        parse: parse, compare: compare, patchOfId: patchOfId,
        fillPatchSelect: fillPatchSelect
    };
})();

var LolData = window.LolData = (function(){
    var store = Object.create(null);     // kind -> key -> payload
    var merged = Object.create(null);    // entry id -> { payload, entry, dataset }
    var pending = Object.create(null);   // file -> Promise (injection in flight or done)
    var written = Object.create(null);   // file -> true (document.written by lolPreloadDataset)
    var CODEC_KIND = "masteries-legacy", NOTES_KIND = "notes";

    function kindOf(entry) { return LolPatches.pageOfId(entry && entry.id); }

    function register(kind, key, payload) {
        if (!store[kind]) store[kind] = Object.create(null);
        store[kind][key] = payload;
    }

    function assign(a, b) {
        var out = {}, k;
        for (k in a) if (Object.prototype.hasOwnProperty.call(a, k)) out[k] = a[k];
        if (b) for (k in b) if (Object.prototype.hasOwnProperty.call(b, k)) out[k] = b[k];
        return out;
    }

    function get(entry) {
        if (!entry || !entry.id) return null;
        var payload = null;
        if (entry.data !== null) {
            var kind = kindOf(entry), table = kind && store[kind];
            payload = table && entry.data in table ? table[entry.data] : null;
            if (!payload) return null;
        }
        var hit = merged[entry.id];
        if (hit && hit.entry === entry && hit.payload === payload) return hit.dataset;
        var ds = assign(entry, payload);
        merged[entry.id] = { entry: entry, payload: payload, dataset: ds };
        return ds;
    }

    function inject(file) {
        if (pending[file]) return pending[file];
        var p = new Promise(function(resolve, reject){
            var s = document.createElement("script");
            s.type = "text/javascript";
            s.async = true;
            s.onload = function(){ resolve(file); };
            s.onerror = function(){
                delete pending[file];
                if (s.parentNode) s.parentNode.removeChild(s);
                reject(new Error("Could not load " + file));
            };
            s.src = file;
            (document.head || document.getElementsByTagName("head")[0] || document.documentElement).appendChild(s);
        });
        pending[file] = p;
        return p;
    }

    function load(entry) {
        return new Promise(function(resolve, reject){
            if (!entry || !entry.id) { reject(new Error("LolData.load: no registry entry")); return; }
            var have = get(entry);
            if (have) { resolve(have); return; }
            if (!entry.file) { reject(new Error("No data file for " + entry.id + " (not built yet)")); return; }
            inject(entry.file).then(function(){
                var ds = get(entry);
                if (ds) resolve(ds);
                else reject(new Error(entry.file + " did not register " + kindOf(entry) + " " + JSON.stringify(entry.data)));
            }, reject);
        });
    }

    function codecsFile() {
        return typeof LOL_REGISTRY !== "undefined" && LOL_REGISTRY && LOL_REGISTRY.codecs || null;
    }

    function getCodec(key) {
        var t = store[CODEC_KIND];
        return t && key in t ? t[key] : null;
    }

    function loadCodec(alias) {
        return new Promise(function(resolve, reject){
            var key = alias && (typeof alias === "string" ? alias : alias.codec);
            if (!key) { reject(new Error("LolData.loadCodec: no codec")); return; }
            var c = getCodec(key);
            if (c) { resolve(c); return; }
            var file = codecsFile();
            if (!file) { reject(new Error("No legacy codec file (not built yet)")); return; }
            inject(file).then(function(){
                var c2 = getCodec(key);
                if (c2) resolve(c2); else reject(new Error(file + " has no codec " + JSON.stringify(key)));
            }, reject);
        });
    }

    function idle(fn) {
        if (typeof window.requestIdleCallback === "function") window.requestIdleCallback(fn, { timeout: 2000 });
        else setTimeout(fn, 200);
    }

    var queue = [], queued = Object.create(null), running = null;
    function prefetch(list) {
        return enqueue((list || []).filter(function(e){
            return e && e.file && e.data !== null && !get(e);
        }).map(function(e){ return e.file; }));
    }

    // --- change notes (data/notes/<page>-<season>.js) ------------------------
    function notesTable(entry) {
        var n = entry && entry.notes, t = store[NOTES_KIND];
        return n && n.key && t && n.key in t ? t[n.key] : undefined;
    }
    function getNotes(entry) {
        var t = notesTable(entry);
        if (t === undefined) return undefined;
        var rec = t && Object.prototype.hasOwnProperty.call(t, entry.patch) ? t[entry.patch] : null;
        return rec || null;
    }
    function loadNotes(entry) {
        return new Promise(function(resolve, reject){
            var n = entry && entry.notes;
            if (!n || !n.key) { reject(new Error("No change notes for " + (entry && entry.id))); return; }
            var have = getNotes(entry);
            if (have !== undefined) { resolve(have); return; }
            if (!n.file) { reject(new Error("No change notes file for " + entry.id + " (not built yet)")); return; }
            inject(n.file).then(function(){
                var rec = getNotes(entry);
                if (rec !== undefined) resolve(rec);
                else reject(new Error(n.file + " did not register notes " + JSON.stringify(n.key)));
            }, reject);
        });
    }
    function prefetchNotes(list) {
        return enqueue((list || []).filter(function(e){
            return e && e.notes && e.notes.file && notesTable(e) === undefined;
        }).map(function(e){ return e.notes.file; }));
    }

    function enqueue(files) {
        files.forEach(function(file){
            if (queued[file] || pending[file]) return;
            queued[file] = true;
            queue.push(file);
        });
        if (running) return running;
        if (!queue.length) return Promise.resolve();
        running = new Promise(function(done){
            var step = function(){
                var file = queue.shift();
                if (!file) { running = null; done(); return; }
                inject(file).then(function(){ idle(step); }, function(){ idle(step); });
            };
            idle(step);
        });
        return running;
    }

    function markWritten(file) { written[file] = true; }
    function wasWritten(file) { return !!written[file]; }

    return {
        register: register, load: load, get: get,
        loadCodec: loadCodec, getCodec: getCodec, codecsFile: codecsFile,
        prefetch: prefetch, kindOf: kindOf,
        loadNotes: loadNotes, getNotes: getNotes, prefetchNotes: prefetchNotes,
        _markWritten: markWritten, _wasWritten: wasWritten
    };
})();

function lolPreloadDataset(page) {
    page = page || LolPatches.page();
    var r = LolPatches.fromHash(page);
    var files = [];
    var e = r.entry;
    if (e && e.data !== null && e.file && !LolData.get(e)) files.push({ file: e.file, entry: e });
    var codecs = LolData.codecsFile();
    if (r.alias && r.alias.codec && codecs && !LolData.getCodec(r.alias.codec)) files.push({ file: codecs, alias: r.alias });
    files.forEach(function(f){
        if (LolData._wasWritten(f.file)) return;
        var wrote = false;
        if (document.readyState === "loading") {
            try {
                document.write('<script type="text/javascript" src="' +
                    String(f.file).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;") + '"><\/script>');
                wrote = true;
            } catch (err) { wrote = false; }
        }
        if (wrote) LolData._markWritten(f.file);
        else if (f.entry) LolData.load(f.entry).then(null, function(){});
        else LolData.loadCodec(f.alias).then(null, function(){});
    });
    return r;
}
